keys:
  - &user age19jq8zjfjtmu0zs63d5dzqzy7tkfrverdk22qjcpf5fvxjtxf9plswyhwa2
  - &host age12e4u495v4y0yeygqfmvqqd2r5073d9qu9w828jv0987ha2c9lyqsjqx5q6

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *user
          - *host
