keys:
  - &user age14jjd8nqghha4awty8ggxqh40rthttewcjs63hfjvpu423k6xx42qu0ykk3
  - &host age12e4u495v4y0yeygqfmvqqd2r5073d9qu9w828jv0987ha2c9lyqsjqx5q6

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *user
          - *host
